version: '2'
services:
    sipunp-app:
        image: sipunp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sipunp-postgresql:5432/sipunp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sipunp-postgresql:
        extends:
            file: postgresql.yml
            service: sipunp-postgresql
