version: '2'
services:
    sipunp-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/sipunp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=sipunp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
